/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paulo
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        xsalada = new javax.swing.JRadioButton();
        xonion = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        xpicanha = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        xburguer = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        xdoritos = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        xbacon = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        queijo = new javax.swing.JCheckBox();
        hamburguer = new javax.swing.JCheckBox();
        bacon = new javax.swing.JCheckBox();
        salada = new javax.swing.JCheckBox();
        barbecue = new javax.swing.JCheckBox();
        maionese = new javax.swing.JCheckBox();
        ketchup = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        coca = new javax.swing.JCheckBox();
        itubaina = new javax.swing.JCheckBox();
        guarana = new javax.swing.JCheckBox();
        agua = new javax.swing.JCheckBox();
        limonada = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtfTotal = new javax.swing.JTextField();
        btnResetar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 19, 19));

        jPanel1.setBackground(new java.awt.Color(22, 22, 22));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\logo.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CALCULE SEU PEDIDO:");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\onion.png")); // NOI18N

        buttonGroup1.add(xsalada);
        xsalada.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xsalada.setForeground(new java.awt.Color(255, 255, 255));
        xsalada.setText("x-Salada");
        xsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsaladaActionPerformed(evt);
            }
        });

        buttonGroup1.add(xonion);
        xonion.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xonion.setForeground(new java.awt.Color(255, 255, 255));
        xonion.setText("x-Onion");
        xonion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xonionActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\picanha.png")); // NOI18N

        buttonGroup1.add(xpicanha);
        xpicanha.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xpicanha.setForeground(new java.awt.Color(255, 255, 255));
        xpicanha.setText("x-Picanha");
        xpicanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpicanhaActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\burger.png")); // NOI18N

        buttonGroup1.add(xburguer);
        xburguer.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xburguer.setForeground(new java.awt.Color(255, 255, 255));
        xburguer.setText("x-Burguer");
        xburguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xburguerActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\doritos.png")); // NOI18N

        buttonGroup1.add(xdoritos);
        xdoritos.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xdoritos.setForeground(new java.awt.Color(255, 255, 255));
        xdoritos.setText("x-Doritos ");
        xdoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xdoritosActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\salada.png")); // NOI18N

        buttonGroup1.add(xbacon);
        xbacon.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        xbacon.setForeground(new java.awt.Color(255, 255, 255));
        xbacon.setText("x-Bacon");
        xbacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbaconActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\paulo\\Documents\\Projetos\\olddog\\img\\bacon.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R$ 23,00");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("R$ 28,00");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("R$ 30,00");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("R$ 28,00");

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("R$ 25,00");

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("R$ 24,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(xdoritos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xsalada))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xonion)
                            .addComponent(jLabel14))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(xpicanha)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(xburguer)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(xbacon))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xonion)
                            .addComponent(xpicanha)
                            .addComponent(xburguer))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xdoritos)
                    .addComponent(xsalada)
                    .addComponent(xbacon))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        queijo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        queijo.setForeground(new java.awt.Color(255, 255, 255));
        queijo.setText("Queijo R$2,50");
        queijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queijoActionPerformed(evt);
            }
        });

        hamburguer.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        hamburguer.setForeground(new java.awt.Color(255, 255, 255));
        hamburguer.setText("Hambúrguer R$5,00");
        hamburguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguerActionPerformed(evt);
            }
        });

        bacon.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        bacon.setForeground(new java.awt.Color(255, 255, 255));
        bacon.setText("Bacon R$3,00");
        bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconActionPerformed(evt);
            }
        });

        salada.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        salada.setForeground(new java.awt.Color(255, 255, 255));
        salada.setText("Salada R$2,50");
        salada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladaActionPerformed(evt);
            }
        });

        barbecue.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        barbecue.setForeground(new java.awt.Color(255, 255, 255));
        barbecue.setText("Barbecue R$1,50");
        barbecue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbecueActionPerformed(evt);
            }
        });

        maionese.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        maionese.setForeground(new java.awt.Color(255, 255, 255));
        maionese.setText("Maionese R$1,50");
        maionese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maioneseActionPerformed(evt);
            }
        });

        ketchup.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ketchup.setForeground(new java.awt.Color(255, 255, 255));
        ketchup.setText("Ketchup R$1,50");
        ketchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketchupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queijo)
                    .addComponent(hamburguer)
                    .addComponent(bacon)
                    .addComponent(salada)
                    .addComponent(barbecue)
                    .addComponent(maionese)
                    .addComponent(ketchup))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(queijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hamburguer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bacon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barbecue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maionese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ketchup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lanches:");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Extras:");

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        jPanel5.setForeground(new java.awt.Color(51, 51, 51));

        coca.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        coca.setForeground(new java.awt.Color(255, 255, 255));
        coca.setText("Coca-Cola 350ml R$5,00");
        coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaActionPerformed(evt);
            }
        });

        itubaina.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        itubaina.setForeground(new java.awt.Color(255, 255, 255));
        itubaina.setText("Itubaina 350ml R$4,50");
        itubaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itubainaActionPerformed(evt);
            }
        });

        guarana.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        guarana.setForeground(new java.awt.Color(255, 255, 255));
        guarana.setText("Guaraná 350ml R$5,00");
        guarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guaranaActionPerformed(evt);
            }
        });

        agua.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        agua.setForeground(new java.awt.Color(255, 255, 255));
        agua.setText("Água 500ml R$3,50");
        agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguaActionPerformed(evt);
            }
        });

        limonada.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        limonada.setForeground(new java.awt.Color(255, 255, 255));
        limonada.setText("Limonada 400ml R$7,00");
        limonada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limonadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coca)
                    .addComponent(itubaina)
                    .addComponent(guarana)
                    .addComponent(agua)
                    .addComponent(limonada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(coca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itubaina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guarana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limonada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bebidas:");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jtfTotal.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jtfTotal.setForeground(new java.awt.Color(0, 102, 204));
        jtfTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTotalActionPerformed(evt);
            }
        });

        btnResetar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnResetar.setForeground(new java.awt.Color(255, 102, 0));
        btnResetar.setText("Resetar");
        btnResetar.setBorderPainted(false);
        btnResetar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(255, 102, 0));
        btnCalcular.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TOTAL: R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("FAÇA SEU PEDIDO:");

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel1))))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 78, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(131, 131, 131))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xsaladaActionPerformed

    private void xonionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xonionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xonionActionPerformed

    private void xpicanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpicanhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xpicanhaActionPerformed

    private void xburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xburguerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xburguerActionPerformed

    private void xdoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xdoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xdoritosActionPerformed

    private void xbaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xbaconActionPerformed

    private void queijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queijoActionPerformed

    private void hamburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hamburguerActionPerformed

    private void baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baconActionPerformed

    private void saladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saladaActionPerformed

    private void barbecueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbecueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barbecueActionPerformed

    private void maioneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maioneseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maioneseActionPerformed

    private void ketchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketchupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketchupActionPerformed

    private void cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocaActionPerformed

    private void itubainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itubainaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itubainaActionPerformed

    private void guaranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guaranaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guaranaActionPerformed

    private void aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aguaActionPerformed

    private void limonadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limonadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limonadaActionPerformed

    private void jtfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double total = 0;
        
        if(xonion.isSelected()){
            total += 28;
        }else if(xpicanha.isSelected()){
            total += 30;
        }else if(xburguer.isSelected()){
            total += 23;
        }else if(xdoritos.isSelected()){
            total += 28;
        }else if(xsalada.isSelected()){
            total += 24;
        }else if(xbacon.isSelected()){
            total += 25;
        }
        
        if(queijo.isSelected()){
            total += 2.50;
        }if(hamburguer.isSelected()){
            total += 5;
        }if(bacon.isSelected()){
            total += 3;
        }if(salada.isSelected()){
            total += 2.50;
        }if(barbecue.isSelected()){
            total += 1.50;
        }if(maionese.isSelected()){
            total += 1.50;
        }if(ketchup.isSelected()){
            total += 1.50;
        }
        
        if(coca.isSelected()){
            total += 5;
        }if(itubaina.isSelected()){
            total += 4.5;
        }if(guarana.isSelected()){
            total += 5;
        }if(agua.isSelected()){
            total += 3.50;
        }if(limonada.isSelected()){
            total += 7;
        }
        
        jtfTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
       buttonGroup1.clearSelection();
       
       queijo.setSelected(false);
       hamburguer.setSelected(false);
       bacon.setSelected(false);
       salada.setSelected(false);
       barbecue.setSelected(false);
       maionese.setSelected(false);
       ketchup.setSelected(false);
       
       coca.setSelected(false);
       itubaina.setSelected(false);
       guarana.setSelected(false);
       agua.setSelected(false);
       limonada.setSelected(false);
       
       jtfTotal.setText("");
    }//GEN-LAST:event_btnResetarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agua;
    private javax.swing.JCheckBox bacon;
    private javax.swing.JCheckBox barbecue;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox coca;
    private javax.swing.JCheckBox guarana;
    private javax.swing.JCheckBox hamburguer;
    private javax.swing.JCheckBox itubaina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JCheckBox ketchup;
    private javax.swing.JCheckBox limonada;
    private javax.swing.JCheckBox maionese;
    private javax.swing.JCheckBox queijo;
    private javax.swing.JCheckBox salada;
    private javax.swing.JRadioButton xbacon;
    private javax.swing.JRadioButton xburguer;
    private javax.swing.JRadioButton xdoritos;
    private javax.swing.JRadioButton xonion;
    private javax.swing.JRadioButton xpicanha;
    private javax.swing.JRadioButton xsalada;
    // End of variables declaration//GEN-END:variables
}
